name: Take hourly underwater snapshot

on:
  schedule:
    # Run at the top of every hour
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token:  ${{ secrets.MY_TOKEN }}
      - name: Set timezone (optional)
        run: echo "TZ=America/Los_Angeles" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: pip install selenium Pillow openai
      - name: Set up Chrome and Chromedriver
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true
          install-dependencies: true
      - name: Update PATH
        run: |
          sudo ln -sf /opt/hostedtoolcache/setup-chrome/chromium/stable/x64/chrome /usr/bin/google-chrome
      - name: Run snapshot script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python grab_snapshot.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "periodic update"
